### ISSUE TITLE
Script etiketinin body yerine head etiketi içerisine taşınması

### ISSUE THREAD

**Issue by ThemeSama** [ismetSANCAKLI/FAQ-Accordion-Card-Html-Css#1]
Yaşam döngüsünün daha iyi anlaşılabilmesi için bu süreci tartışalım.

**Comment by ismet-sancakli** [comment]
Javascript kodu </body> tag inin hemen üzerinde yer alması günümüzde oldukça yaygın kullanılan bir yöntemdir. Bunun sebeplerinden bir tanesi javascript koduna gelene kadar DOM ' un yüklenmiş olmasıdır ayrıca buradaki javascript kodu da DOM 'un bir parçasıdır. Ancak biz javascript kodumuzu HTML' de etiketlerin üzerine taşıdığımız zaman javascript kodu konsolda çalışmasına rağmen o anda herhangi bir "input" bulamadığı için "event" ataması yapamıyor.  Bundan dolayı kodun oluşturmasını beklediğimiz etkiyi göremiyoruz. Bunun için javascript dosyası içerisinde DOM oluşumunu beklemesi ve daha sonra çalışması için bir "evetListener" ve içerisine "DOMContentLoaded" komutunu ekliyoruz. Böylece artık javascript kodu içerisinde bulunan selector inputlara erişebilecek ve beklediğimiz sonucu görebileceğiz.
