### ISSUE TITLE
Gölge ve çizgilerin taşmalarının engellenmesi

### ISSUE THREAD

**Issue by ThemeSama** [ismetSANCAKLI/FAQ-Accordion-Card-Html-Css#4]
Sol tarafta bulunan imaj altında yer alan gölge ve çizgilerin kutu dışına taşmasının engellenmesi gerekmektedir.

**Comment by ismet-sancakli** [comment]
Geri bildiriminiz için teşekkür ederim. Gerekli çalışmalar tapıldı.
