### ISSUE TITLE
FAQ için girilen çok uzun cevaplarda cevabın tamamı görünmüyor

### ISSUE THREAD

**Issue by ThemeSama** [ismetSANCAKLI/FAQ-Accordion-Card-Html-Css#5]
Tıkladığımızda açılan içerikte cevap metni çok uzunsa hepsini göremiyoruz.

**Comment by ismet-sancakli** [comment]
Bunun sebebi kutucuklar için belirtilen alanın statik olmasından kaynaklanıyordu ancak şu anda alan dinamik hale getirildiği için içeriğin fazla olması bir problem oluşturmayacaktır.
