### ISSUE TITLE
Soru metni uzun olduğunda sağındaki ok ortalanmıyor

### ISSUE THREAD

**Issue by ThemeSama** [ismetSANCAKLI/FAQ-Accordion-Card-Html-Css#6]
Soru metninin uzun olduğu durumlarda sağ tarafında yer alan ok simgesinin soru metnine göre dikeyde ortalanması gerekmektedir.

**Comment by ismet-sancakli** [comment]
Öncelikle geri bildiriminiz için teşekkür ederim. Burada ki düzeltmeyi label etiketi içerisinde bulunan display: block  özelliğini bize yatay konumlandırma da esneklik sağlayan display: flex kullandık. Ayrıca display: flex ile birlikte align-items: center kullanarak ok işaretini istediğimiz konuma getirebiliyoruz.
