### ISSUE TITLE
Soru ve cevap metinlerinde dikey boşluklar eşit değil

### ISSUE THREAD

**Issue by ThemeSama** [ismetSANCAKLI/FAQ-Accordion-Card-Html-Css#7]
Soru ve cevaplar için dikey boşlukları eşitlemek tasarımın daha profesyonel görünmesini sağlayacaktır.

**Comment by ismet-sancakli** [comment]
İçerikleri oluşturan kutucuk boyutu statik olduğu için boşluk eşitlenmesi her yerde aynı değildi ancak şu anda verdiğimiz statik değerleri dinamik hale getirdik ve boşluklar eşitlenmiş oldu.
